version: '3.7'
services:

  nginx:
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/web.conf
      - ./:/app

  watch:
    command: >
      /bin/bash -c 'npm install --include=dev && npm run dev'

  web:
    command: uvicorn --host 0.0.0.0 --port 8000 semantic_mitopen.main:app --reload
