version: '3.7'
services:

  nginx:
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/web.conf
      - ./:/app

  watch:
    command: >
      /bin/bash -c 'npm install --include=dev && npm run dev'

  web:
    command: gunicorn -b 0.0.0.0:8000 -w 3 -k uvicorn.workers.UvicornWorker semantic_mitopen.main:app --reload